### ISSUE TITLE
US 03.01.01 - Generate QR codes

### ISSUE THREAD

**Issue by tpbach** [CMPUT301W21T24/PenguinDive#14]
Partial User Story: As an experimenter, I want to be able to generate QR codes that I can print for a specific experiment and trial 				 result (for instance PASS for a binomial trial I subscribed to). 
	
Rationale: An experimenter can take a QR code to anywhere and show their experiment results to others.
	
Weight (1-10): 8 (may take a significant portion of time to get working) 14 days to build
	
Risk level (low, medium, high): low

**Comment by rbrooks1** [comment]
In progress.  Generating QR codes works, saving still to be done

**Comment by rbrooks1** [comment]
Saving is now working
