### ISSUE TITLE
US 03.02.01 - Scan QR codes

### ISSUE THREAD

**Issue by tpbach** [CMPUT301W21T24/PenguinDive#15]
Partial User Story: As an experimenter, I want to be able scan QR codes to indicate success or failure, or increment counts for trials I subscribed to.
	
Rationale: Experimenter should be able to scan QR codes to indicate success or failure, or increment counts for trials experimenter subscribed to for convenience. 
	
Weight (1-10): 8 (Will need to use some API to scan the QR code) 7-14 days to build.
	
Risk level (low, medium, high): medium

**Comment by rbrooks1** [comment]
QR scanning works, nothing done with the scanned text currently

**Comment by rbrooks1** [comment]
Will not have QR updating experiments done for project part 3; however, the basic functionality for scanning QR codes it available.
